#!/bin/bash
# Get directory.
dir="$(dirname "$0")"

echo "Generating authorized keys from local public key."
cp "$HOME/.ssh/id_rsa.pub" "$dir/authorized_keys"
echo "Generated authorized keys from local public key." ; echo

echo "Fixing permissions."
chmod 600 "$dir/authorized_keys"
echo "Fixed permissions."
