#!/bin/bash
# Iterate hosts.
for host in $@
do
  echo "Installing host '$host'."

  # Install authorized keys.
  echo "Installing authorized keys to user 'root@$host'."
  cat "$HOME/.ssh/id_rsa.pub" | ssh "root@$host" "mkdir -p .ssh ; chmod 700 .ssh ; cat > .ssh/authorized_keys ; chmod 600 .ssh/authorized_keys"
  echo "Installed authorized keys to user 'root@$host'." ; echo

  # Check for existence of configuration directory.
  if [ -d "$(dirname "$0")/etc" ]
  then
    # Transfer configuration directory.
    echo "Transferring configuration directory to host '$host'."
    scp "$(dirname "$0")/etc/*" "root@$host:/etc/"
    echo "Transferred configuration directory to host '$host'." ; echo
  fi

  # Upgrade packages.
  echo "Upgrading packages of host '$host'."
  ssh "root@$host" "yum upgrade --assumeyes --nogpgcheck ; yum autoremove --assumeyes"
  echo "Upgraded packages of host '$host'." ; echo

  # Reboot host.
  echo "Rebooting host '$host'."
  ssh "root@$host" "reboot"
  echo "Rebooted host '$host'." ; echo

  echo "Installed host '$host'."
done
